CREATE TABLE t_mt_sys_ver (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  version     VARCHAR(20) NOT NULL,
  description TEXT,
  created_at  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO t_mt_sys_ver (version, description) VALUES
('1.0.000', 'First initialization for database');