CREATE TABLE t_mt_country (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  country_code VARCHAR(10) NOT NULL,
  country_name VARCHAR(100) NOT NULL,
  created_at  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO t_mt_country (country_code, country_name) VALUES
('MY', 'Malaysia'),
('US', 'United States'),
('CA', 'Canada'),
('GB', 'United Kingdom'),
('AU', 'Australia'),
('FR', 'France'),
('DE', 'Germany'),
('IT', 'Italy'),
('ES', 'Spain'),
('JP', 'Japan'),
('CN', 'China'),
('IN', 'India'),
('BR', 'Brazil'),
('MX', 'Mexico'),
('NZ', 'New Zealand'),
('SG', 'Singapore'),
('HK', 'Hong Kong'),
('AE', 'United Arab Emirates'),
('KR', 'South Korea'),
('TH', 'Thailand'),
('NL', 'Netherlands');
