CREATE TABLE t_mt_clauses (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  clause_code VARCHAR(50) NOT NULL,
  clause_text TEXT,
  country_id  BIGINT,
  created_at  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_t_mt_clauses_country FOREIGN KEY (country_id) REFERENCES t_mt_country(id)
);
